[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y python3-pip",
    "pip install --upgrade pip"
]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "echo 'Building application...'"
]

[start]
cmd = "python app.py"